name: plans_tracker
description: A project which tracks my progress

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  equatable: ^2.0.3
  flutter_scale_tap: ^1.0.5
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  shared_preferences: ^2.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true